version: "3.1"

language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 3
  max_ngram: 5
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
- name: RulePolicy
  core_fallback_action_name: "action_default_fallback"
  core_fallback_threshold: 0.4  # Lower this if Core fallback doesn't trigger
  enable_fallback_prediction: True
- name: "TEDPolicy"
  max_history: 5
  epochs: 100

assistant_id: 20241104-151219-elaborate-kudos




 

